kind: Service
apiVersion: v1
metadata:
  name: otus-order-service
spec:
  type: ExternalName
  externalName: otus-order-service.order-service.svc.cluster.local
---
kind: Service
apiVersion: v1
metadata:
  name: otus-delivery-service
spec:
  type: ExternalName
  externalName: otus-delivery-service.delivery-service.svc.cluster.local
---
kind: Service
apiVersion: v1
metadata:
  name: otus-inventory-service
spec:
  type: ExternalName
  externalName: otus-inventory-service.inventory-service.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: otus-order-service
                port:
                  number: 80
          - path: /deliveries
            pathType: Prefix
            backend:
              service:
                name: otus-delivery-service
                port:
                  number: 80
          - path: /items
            pathType: Prefix
            backend:
              service:
                name: otus-inventory-service
                port:
                  number: 80