{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "billing-service.fullname" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "billing-service.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "billing-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 10s
      port: http
      path: /actuator/prometheus
{{- end }}